### ISSUE TITLE
FIX:  Token Driver will not start - validation errors

### ISSUE THREAD

**Issue by TheLastCicada** [Chia-Network/climate-token-driver#56]
When running the pre-compiled binaries on Linux, or installing from source on the `main` branch, the token driver fails to start with the following error:

```
Traceback (most recent call last):
  File "/home/zachary/tmp/climate-token-driver/app/main.py", line 9, in <module>
    from app.api import v1
  File "/home/zachary/tmp/climate-token-driver/app/api/v1/__init__.py", line 1, in <module>
    from app.api.v1.core import router
  File "/home/zachary/tmp/climate-token-driver/app/api/v1/core.py", line 3, in <module>
    from app.api.v1 import activities, cron, keys, tokens, transactions
  File "/home/zachary/tmp/climate-token-driver/app/api/v1/activities.py", line 7, in <module>
    from app import crud, models, schemas
  File "/home/zachary/tmp/climate-token-driver/app/crud/__init__.py", line 1, in <module>
    from app.crud.chia import BlockChainCrud, ClimateWareHouseCrud  # noqa
  File "/home/zachary/tmp/climate-token-driver/app/crud/chia.py", line 13, in <module>
    from app import schemas
  File "/home/zachary/tmp/climate-token-driver/app/schemas/__init__.py", line 1, in <module>
    from app.schemas.activity import (  # noqa
  File "/home/zachary/tmp/climate-token-driver/app/schemas/activity.py", line 8, in <module>
    from app.schemas.token import TokenOnChain
  File "/home/zachary/tmp/climate-token-driver/app/schemas/token.py", line 11, in <module>
    from app.schemas.payment import (
  File "/home/zachary/tmp/climate-token-driver/app/schemas/payment.py", line 7, in <module>
    from app.config import settings
  File "/home/zachary/tmp/climate-token-driver/app/config.py", line 112, in <module>
    settings = get_settings()
  File "/home/zachary/tmp/climate-token-driver/app/config.py", line 107, in get_settings
    settings = Settings(**settings_dict)
  File "pydantic/env_settings.py", line 39, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 2 validation errors for Settings
CLIMATE_API_KEY
  extra fields not permitted (type=value_error.extra)
CLIMATE_API_URL
  extra fields not permitted (type=value_error.extra)
```

**Comment by fizpawiz** [comment]
@TheLastCicada - is this still an issue?

**Comment by TheLastCicada** [comment]
@fizpawiz yes, still an issue, I tried it again just now.  Craig also saw the same issue on his machines.

**Comment by TheLastCicada** [comment]
Closing this issue - I believe the problem was an old config file that hadn't been updated to the latest version.
